"""Core implementation of the Hierarchical GM pre-filter.

This module provides the fixed-base hierarchical pre-filter used in the
accompanying SN Computer Science manuscript. The implementation marks
composites generated by a reproducible fourteen-base configuration before
counting or forwarding the remaining candidates to a later primality-testing
stage.
"""

import math
import numpy as np
from numba import njit, prange, set_num_threads, get_num_threads

__version__ = "1.0"

try:
    set_num_threads(min(8, get_num_threads()))
except ValueError:
    pass

LAYER_BASES = np.array([2, 3, 5, 7, 11, 4, 6, 8, 9, 10, 12, 15, 18, 20], dtype=np.int64)


@njit(fastmath=True, cache=True)
def is_prime(n):
    if n < 2:
        return False
    if n == 2 or n == 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


@njit(parallel=True, fastmath=True, cache=True)
def segmented_gm_prefilter_numba(low, high, segment_size=1_000_000):
    """Count candidate primes after applying the fixed-base HGM pre-filter.

    The function processes the inclusive interval ``[low, high]`` in segments.
    For every segment, it allocates a compact byte marking array, marks all
    values generated by the fixed ``LAYER_BASES`` configuration, and then counts
    the unmarked values that pass the local deterministic ``is_prime`` check.
    The marking rule starts at ``2 * b`` for prime bases so that the prime base
    itself is not rejected, and at ``b`` for composite bases so that composite
    bases are rejected consistently with the manuscript description.

    Parameters
    ----------
    low : int
        Inclusive lower bound of the interval to be processed.
    high : int
        Inclusive upper bound of the interval to be processed. If ``high`` is
        smaller than ``low``, the function returns zero.
    segment_size : int, optional
        Maximum number of integer positions processed in each segment. The
        default value is ``1_000_000``, which keeps memory usage bounded while
        preserving reproducible benchmark behavior.

    Returns
    -------
    int
        Number of unmarked values in ``[low, high]`` that are classified as
        prime by the internal primality check after HGM marking. This return
        value is intended for reproducible benchmarking and validation of the
        pre-filtered pipeline, not as a standalone primality certificate for
        arbitrary cryptographic-size integers.
    """
    if high < low:
        return 0
    total_size = high - low + 1
    segment_count = (total_size + segment_size - 1) // segment_size
    total_primes = 0

    for segment_index in prange(segment_count):
        seg_start = low + segment_index * segment_size
        seg_end = min(seg_start + segment_size - 1, high)
        size = seg_end - seg_start + 1
        marked = np.zeros(size, dtype=np.uint8)

        for base in LAYER_BASES:
            if base > seg_end:
                continue
            k_start = 2 if is_prime(base) else 1
            first_multiple = max(base * k_start, ((seg_start + base - 1) // base) * base)
            for m in range(first_multiple, seg_end + 1, base):
                marked[m - seg_start] = 1

        local_primes = 0
        for i in range(size):
            if marked[i] == 0 and is_prime(seg_start + i):
                local_primes += 1
        total_primes += local_primes

    return total_primes


def count_primes(low=1, high=1_000_000, segment_size=1_000_000):
    return segmented_gm_prefilter_numba(low, high, segment_size)


if __name__ == "__main__":
    print(count_primes(1, 100_000, 10_000))
